[package]
name = "brogue-scanner"
version = "0.9.6"
authors = ["ArchTangent"]
edition = "2018" 

[dependencies]
anyhow = "1"
clap = "2"
csv = "1"
encoding_rs = "0.8"
encoding_rs_io = "0.1"
fastrand = "2"
